name: build
run-name: build on github
on:
  push:
    tags:
      - 'v*'


env:
  REPO_URL: https://github.com/kalous12/action_test.git
  REPO_BRANCH: main
  TZ: Asia/Shanghai

  
jobs:

  Build:
    runs-on: ubuntu-22.04
    timeout-minutes: 1440
    steps:
      
    - name: Checkout
      uses: actions/checkout@v3

    - name: Show system
      run: |
        echo -e "Total CPU cores\t: $(nproc)"
        cat /proc/cpuinfo | grep 'model name'
        free -h
        uname -a
        [ -f /proc/version ] && cat /proc/version
        [ -f /etc/issue.net ] && cat /etc/issue.net
        [ -f /etc/issue ] && cat /etc/issue
        ulimit -a    

    - name: Clone Source Code
      run: |
        df -hT $PWD
        git clone $REPO_URL

    - name: install dependency
      run: |
        sudo apt update
        sudo apt-get install -y gcc-aarch64-linux-gnu

    - name: complie
      run: |
        mkdir output
        aarch64-linux-gnu-gcc -o hello action_test/hello.c
        echo "FIRMWARE=output" >> $GITHUB_ENV
      
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Generate release tag
      id: tag
      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
      run: |
          echo "release_tag=${{ github.ref }}" >> $GITHUB_OUTPUT
          echo "release_date=$(date +"%Y.%m.%d")" >> $GITHUB_OUTPUT
          touch release.txt
          echo "后台地址：192.168.11.1
                full   = 全插件
                docker = 带docker
                slim   = 精简版
                beggar = 乞丐版" >> release.txt
          echo "status=success" >> $GITHUB_OUTPUT
        
    - name: Upload firmware to release
      uses: softprops/action-gh-release@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          name: ${{ steps.tag.outputs.release_date }} DoorNet_linux-5.4_固件下载
          tag_name: ${{ steps.tag.outputs.release_tag }}
          body_path: release.txt
          files: ${{ env.FIRMWARE }}/*

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
          retain_days: 1
          keep_minimum_runs: 1

    - name: Remove old Releases
      uses: dev-drprasad/delete-older-releases@v0.2.1
      with:
          keep_latest: 20
          delete_tags: true
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Delete Artifacts
      uses: geekyeggo/delete-artifact@v2
      with:
         name: |
            bin-archive
        
       
